name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (change if you want a different branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend/ --build
        docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend/ --build
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend/ --push
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend/ --push

    - name: Deploy to Staging EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.STAGING_EC2_SSH_KEY }} ec2-user@${{ secrets.STAGING_EC2_PUBLIC_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker run -d --name backend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/backend:latest
        EOF

    - name: Deploy to Production EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRODUCTION_EC2_SSH_KEY }} ec2-user@${{ secrets.PRODUCTION_EC2_PUBLIC_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker run -d --name backend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/backend:latest
        EOF
